apiVersion: v1
kind: Pod
metadata:
    name: redis
    labels:
        app: voting-app
spec:
    containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
