apiVersion: v1
kind: Service
metadata:
    name: sservice-for-vote
    labels:
        name: service-for-vote
        app: voting-app
spec:
    type: NodePort
    ports: 
        - port: 80
          targetPort: 80
          nodePort: 30001
    selector:
        name: kodekloud-voting-app
        app: voting-app
