apiVersion: v1
kind: Service
metadata:
    name: sservice-for-result
    labels:
        name: service-for-result
        app: voting-app
spec:
    type: NodePort
    ports: 
        - port: 80
          targetPort: 80
          nodePort: 30004
    selector:
        name: kodekloud-result
        app: voting-app
