apiVersion: v1
kind: Pod
metadata:
    name: kodekloud-voting-app
    labels:
        name: kodekloud-voting-app
        app: voting-app
spec:
    containers:
        - name: kodekloud-voting-app
          image: kodekloud/examplevotingapp_vote
          ports:
            - containerPort: 80

