apiVersion: v1
kind: Pod
metadata:
    name: kodekloud-worker
    labels:
        name: kodekloud-worker
        app: voting-app
spec:
    containers:
        - name: kodekloud-worker
          image: dockersamples/worker
